FROM node:19

# Créer un répertoire pour l'application
WORKDIR /usr/src/app

# Installer les dépendances de l'application
COPY package*.json ./
RUN npm install

# Copier les fichiers de l'application
COPY . .

# Exposer le port 3000
EXPOSE 3000

# Démarrer l'application en mode de développement
CMD ["npm", "run", "start:dev"]
